extends:
  - "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    - [
        "test",
        "feat",
        "fix",
        "chore",
        "build",
        "docs",
        "refactor",
        "style",
        "ci",
        "perf",
        "wip",
      ]
